### ISSUE TITLE
_balances is not defined

### ISSUE THREAD

**Issue by AliWisam** [stvndf/Card-NFT-marketplace#1]
Where are you calling it from?

There is no mapping for this. Are you calling it from base contract? That is private, we cannot use that mapping in base contract.

DeclarationError: Undeclared identifier.
   --> SignatureMP/NewNftTest.sol:212:9:
    |
212 |         _balances[id][msg.sender] += 1;
    |         ^^^^^^^^^

**Comment by stvndf** [comment]
I think back when I wrote this contract I had manually edited the imported ERC1155 contract (not generally recommended practice, but it was a simple solution to solve a particular issue) to make _balances `internal` instead of `private`
